server:
  port: 8082

logging:
  level:
    root: INFO
    org.springframework.web: INFO

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/vendify
    username: postgres
    password: sspostgres2022